
import armazem.ArmazemCopo;
import armazem.ArmazemIngrediente;
import armazem.ArmazemMoeda;
import core.Armazem;
import core.Mensagens;
import java.util.logging.Level;
import java.util.logging.Logger;
import programa.Maquina;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iderli
 */
public class OperacaoMaquina extends javax.swing.JFrame {

    Maquina cafeteira = null;
    InterfaceGrafica interfaceGrafica = null;
    
    /**
     * Creates new form OperacaoMaquina
     */
    public OperacaoMaquina(Maquina cafeteira, InterfaceGrafica interfaceGrafica) {
       this.interfaceGrafica = interfaceGrafica;
        this.cafeteira = cafeteira;
        initComponents();
        mostrarRecursos();

    }

    private OperacaoMaquina() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        listview = new java.awt.List();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listviewMouseClicked(evt);
            }
        });
        listview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listviewActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar Maquina para dados iniciais");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addComponent(listview, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listview, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        interfaceGrafica.setVisible(true);
        this.setVisible(false);
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listviewMouseClicked

       

 
    }//GEN-LAST:event_listviewMouseClicked

    private void listviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listviewActionPerformed

    }//GEN-LAST:event_listviewActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           
        listview.clear();
        cafeteira.parserArquivo();
        Mensagens mensagens = new Mensagens();
        mensagens.mensagemTela("Verificando recursos necessarios para reposiçao");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(OperacaoMaquina.class.getName()).log(Level.SEVERE, null, ex);
        }
        mensagens.mensagemTela("Atualizando recursos no Estoque");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(OperacaoMaquina.class.getName()).log(Level.SEVERE, null, ex);
        }
        mensagens.mensagemTela("Reposiçao realizada com sucesso");
        mostrarRecursos();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacaoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacaoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacaoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacaoMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacaoMaquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private java.awt.List listview;
    // End of variables declaration//GEN-END:variables

    private void mostrarRecursos() {
        
        listview.add("Copos");
        for(int i=0;i<cafeteira.objDispensa.dispensaCopo.size();i++){
            listview.add("Copo : " + cafeteira.objDispensa.dispensaCopo.get(i).getCopo().getNome() +
                               " | Volume : " + cafeteira.objDispensa.dispensaCopo.get(i).getCopo().getVolume() + " ml " +
                               " | Quantidade Atual: " + cafeteira.objDispensa.dispensaCopo.get(i).getQuantidade() +
                               " | Quantidade Máxima: " + cafeteira.objDispensa.dispensaCopo.get(i).getQuantidadeMax() +
                               " | Quantidade Mínima: " + cafeteira.objDispensa.dispensaCopo.get(i).getQuantidadeMin());
        }
        listview.add("Ingredientes");
        for(int i=0;i<cafeteira.objDispensa.dispensaIngrediente.size();i++){
            listview.add("Ingrediente : " + cafeteira.objDispensa.dispensaIngrediente.get(i).getIngrediente().getNome()
                    + " | Unidade : " + cafeteira.objDispensa.dispensaIngrediente.get(i).getIngrediente().getUnidade()
                    + " | Quantidade Atual: " + cafeteira.objDispensa.dispensaIngrediente.get(i).getQuantidade()
                    + " | Quantidade Máxima: " + cafeteira.objDispensa.dispensaIngrediente.get(i).getQuantidadeMax()
                    + " | Quantidade Mínima: " + cafeteira.objDispensa.dispensaIngrediente.get(i).getQuantidadeMin());
        }
        
        
        listview.add("Moedas");

        
        for(int i=0;i<cafeteira.objCofre.moedasInternas.size();i++){
            listview.add("Moeda : " + cafeteira.objCofre.moedasInternas.get(i).getMoeda().getNome()
                    + " | Valor : " + cafeteira.objCofre.moedasInternas.get(i).getMoeda().getValor()
                    + " | Quantidade Atual: " + cafeteira.objCofre.moedasInternas.get(i).getQuantidade()
                    + " | Quantidade Máxima: " + cafeteira.objCofre.moedasInternas.get(i).getQuantidadeMax()
                    + " | Quantidade Mínima: " + cafeteira.objCofre.moedasInternas.get(i).getQuantidadeMin());
        }
    }

    
}
